version: '3'

services:
  nest:
    container_name: api_nest_mks
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "sleep 10 && npm run start:dev"
    ports:
      - '${API_PORT}:3000'
    volumes:
      - .:/usr/app
    networks:
      - mks_networks
    depends_on:
      - postgres
      - redis

  postgres:
    container_name: db_postgres_mks
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '${DB_PORT}:5432'
    networks:
      - mks_networks

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      - mks_networks

networks:
  mks_networks:
    driver: bridge
